name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Enable corepack and install Yarn 4.1.1
        run: |
          corepack enable
          corepack prepare yarn@4.1.1 --activate

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test
